# Generated by Django 6.0.5 on 2026-06-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='product_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
