# Generated by Django 6.0.5 on 2026-06-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_uuid',
            field=models.CharField(max_length=200),
        ),
    ]
