# Generated by Django 6.0.5 on 2026-05-20 08:51

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_subcategory_proeduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proeduct',
            name='desc',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
