# Generated by Django 6.0.5 on 2026-05-21 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='proeduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.brand'),
        ),
    ]
