# Generated by Django 6.0.5 on 2026-05-21 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_proeduct_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='proeduct',
            name='brand',
        ),
        migrations.AddField(
            model_name='proeduct',
            name='brands',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.brand'),
        ),
    ]
