# Generated by Django 6.0.5 on 2026-05-21 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_brand_subcategory_remove_proeduct_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subcategory'),
        ),
    ]
